### ISSUE TITLE
main script missed parameters, but docs provide them

### ISSUE THREAD

**Issue by exocode** [NigelOToole/direction-reveal#13]
`animationPostfixEnter` and `animationPostfixLeave` are missed in the main script, but is mentioned in the docs/readme as well in `/docs/script`

When I use the usage script: 

```javascript
const directionRevealDefault = DirectionReveal({
  selector: '.direction-reveal',
  itemSelector: '.direction-reveal__card',
  animationName: 'swing',
  animationPostfixEnter: 'enter',
  animationPostfixLeave: 'leave',
  enableTouch: true,
  touchThreshold: 250
});
```

The `animationPostfixEnter` and `animationPostfixLeave` is not picked up. The generated classes are still `out`and `leave` and not `enter`and `leave` 

It took me hours to find that out :-) , please be so kind and fix that to help others who stumble over this problem

PS: For libraries which uses static page generators (eg: React, Gatsby,...) `document`and `window`are not defined while build time, so a check for `document` in line around 23 makes it possible to use your script/library "out-of-the-box": 

`const containers = typeof document !== "undefined" ? document.querySelectorAll(selector) : []`

**Comment by notoole-vccp** [comment]
Thanks for raising this issue. I have updated the plugin with those parameters, an older version was in NPM. 

For static site generators Im not sure if that check should be done in this script or done in the site itself. I dont want to add code thats specific to a particular build process. Do you have any references for this fix so I can look into further?
