### ISSUE TITLE
Bug on mouse hover on right side of direction-reveal__card

### ISSUE THREAD

**Issue by atlanteavila** [NigelOToole/direction-reveal#3]
Hey there, great plugin! I have installed this on my react app and seems to be working great! I have one issue: when I mouse over the right side of my images no matter where I exit, up or down, the animation it brings up is always swing--out-right or swing--in-right. See in the screenshots, I went from the top to the bottom of the two sandwiches on the left of the screen. Strangely though, if I do it on the left half of the images, they work just fine. Any help or insight would be greatly appreciated!

Thanks again for the useful script!

Atlante
<img width="1104" alt="screen shot 2018-02-15 at 4 00 11 am" src="https://user-images.githubusercontent.com/1652309/36255740-1399eddc-1205-11e8-8c37-55caf9e90731.png">
<img width="1104" alt="screen shot 2018-02-15 at 3 59 56 am" src="https://user-images.githubusercontent.com/1652309/36255742-13d043b4-1205-11e8-9d48-6e91acaf0dc8.png">

**Comment by Kukustar** [comment]
@NigelOToole Hello, can you paste some where example of  installed this plugin in react app. 
I'm try to make the same and have some problems with it.

**Comment by NigelOToole** [comment]
Hey @atlanteavila, thanks for your kind comments. This could be a number of things but the script can sometimes be inaccurate due the the way the browser debounces the reporting of mouse movements. To help combat this you can see in my layout example I used a transparent border around my cards to increase the area for the mouse to interact with. Try and see if this helps, if you are able to find another way to increase the accuracy of the script please pass it on.

**Comment by NigelOToole** [comment]
Hey @Kukustar, I think you can import it as you would any other module in React although I have not tested this in React myself.

**Comment by atlanteavila** [comment]
Thanks @NigelOToole, I have figured out that it only works with perfect squares... I have to try to find some time to see if I can come up with a fix but due to time constraints I can't promise anything... Thanks!

**Comment by atlanteavila** [comment]
@Kukustar run `$ npm install direction-reveal --save` once installed, import it to your component: `import DirectionReveal from 'direction-reveal';` then in component did update:

 ```
DirectionReveal({
            selector: '.direction-reveal',              // Container element selector.
            itemSelector: '.direction-reveal__card',    // Item element selector.
            animationName: 'swing',                     // Animation CSS class.
            enableTouch: true,                          // Adds touch event to show content on first click then follow link on the second click.
            touchThreshold: 250                         // Touch length must be less than this to trigger reveal which prevents the event triggering if user is scrolling.
        });
```

Hope that helps!

Atlante

**Comment by NigelOToole** [comment]
Hey @atlanteavila, yes the script is intended for use with squares. It will still work with rectangular shapes but is less likely to be accurate. Hope you can find a fix for you.

**Comment by WTVader** [comment]
The problem is the wrong calculation of x/y (line 33, 34 in direction-reveal.js). The right parenthesis for the normalization is set wrong. Correct calculation:
let x = (e.pageX - position.x - (w / 2)**)** * (w > h ? (h / w) : 1);
let y = (e.pageY - position.y - (h / 2)**)** * (h > w ? (w / h) : 1);
This causes a correct normalization for aspect ratios of the hovered element not equal 1. And subsequently the correct calculation of the direction.
